[package]
name = "stateright"
version = "0.3.0"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
license = "MIT"
edition = "2018"

description = "A library for specifying state machines and model checking invariants."
repository = "https://github.com/stateright/stateright"
readme = "README.md"
categories = ["algorithms", "concurrency", "development-tools", "network-programming", "simulation"]
keywords = ["actor", "distributed-systems", "model-checking", "paxos"]

[dependencies]
crossbeam-utils = "0.6.6"
difference = "2.0.0"
fxhash = "0.2.1"
num_cpus = "1.10.1"
regex = "1.2.1"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"

[dev-dependencies]
clap = "2.33.0"
