[package]
name = "stateright"
version = "0.0.0"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
license = "MIT"

description = "A library for specifying state machines and model checking invariants."
repository = "https://github.com/stateright/stateright"
readme = "README.md"
categories = ["development-tools"]
keywords = ["model-checking"]

[dependencies]
fxhash = "0.2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
clap = "2.30.0"
